apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ticket_project/payment
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: "http://nats-srv:4333"
            - name: NATS_CLUSTER_ID
              value: nats
            - name: MONGO_URI
              value: mongodb://payment-mongo:27017/ticket_app
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: ticket-app-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: ticket-app-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 5054
      targetPort: 5054
