apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets_encrypt_prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hoctap.tranthanhbinh@gmail.com
    privateKeySecretRef:
      name: lets_encrypt_prod
    solvers:
      - http01:
          ingress:
            class: nginx
