# Tạo file "jwt-secret.yaml" rồi thực hiện điền vào các placeholder
# Chú ý encoding base64 key trước
# Lấy key base64: [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes((Read-Host 'Nhập chuỗi')))

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  JWT_KEY: <BASE64_ENCODED_SECRET>
  STRIPE_KEY: <BASE64_ENCODED_SECRET>
