name: test_after_merge

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd auth
          echo "@${{ github.actor }}:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_INSTALL_SECRET }}" >> ~/.npmrc
          cat ~/.npmrc
          cat package.json
          npm install && npm run test:ci
