name: test_after_merge

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace values
        shell: bash
        env:
          PAT: ${{ secrets.PACKAGE_INSTALL_SECRET }}
        run: |
          sed -i.back "s|PACKAGE_INSTALL_SECRET|${PAT}|g" ./.npmrc
      - run: |
          cd auth && npm install && npm run test:ci
